name: New release app

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag-version:
        description: 'The tag version, branch name or SHA to checkout'
        required: true

jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compress repo to Tar
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./
          outPath: pwa.tar.gz

      - name: Upload File
        id: upload
        uses: JantHsueh/upload-file-action@1.0
        with:
          url: "https://pwapublish.plentysystems.com/storeDefaultApplication"
          forms: '{ "token": "${{ secrets.SUPPLIER_TOKEN }}" }'
          fileForms: '{ "file": "pwa.tar.gz" }'

